name: "Infrastructure Setup"
description: "Credentials and Terraform"

inputs:
  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
    required: true
  ssh-key:
    description: "SSH private key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ inputs.role-to-assume }}
        role-duration-seconds: 1200
        role-session-name: acuity-actions-cicd
    - name: "Setup - Terraform CLI"
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.5
        terraform_wrapper: false
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh-key }}
        known_hosts: github.com
    - name: "Setup - Terraform compliance"
      uses: terraform-compliance/github_action@main