name: "Infrastructure Nuke"

runs:
  using: "composite"
  steps:      
      - name: "Setup - Cloud Nuke"
        run: brew install cloud-nuke
        shell: sh
      - name: "Run - Cloud Nuke"
        run: |
          cloud-nuke aws \
            --region us-east-1 \
            --exclude-resource-type s3 \
            --exclude-resource-type iam \
            --exclude-resource-type secretsmanager
        # --config ${{ github.action_path }}/config.yml
        shell: sh