name: Build Image


inputs:
  repository:
    description: “Name of the repository to cache the build image”
    required: true
  deliverable:
    description: “Type of the image to cache”
    required: true

env:
  CACHE_IMAGE: ghcr.io/${{ inputs.repository }}
  DOCKER_BUILDKIT: 1

runs:
  using: "composite"
  steps:
    - name: Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build
      run: |
        docker build \
          --cache-from ${{ inputs.repository }}:cicd-${{ inputs.deliverable }} \
          --tag ${{ inputs.repository }}:cicd-${{ inputs.deliverable }} \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          "${{ github.action_path }}/${{ inputs.deliverable }}/."
    - name: Push
      run: docker push ${{ inputs.repository }}:cicd-${{ inputs.deliverable }}