name: "Python Notebook Bandit"
description: "Scan converted notebooks for known vulnerabilities."

inputs:
  notebooks-path:
    description: “Path to notebooks”
    required: true
  python-version:
    description: "Python version to use"
    default: '3.9'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
        architecture: x64
    - name: Configure Environment
      run: |
        python -m pip install -U pip
        python -m pip install packaging==21.3
        python -m pip install nbconvert==6.4.5
        python -m pip install bandit==1.7.4
        find . \
          -type f -name "*.ipynb" \
          -exec jupyter-nbconvert \
          --to python \
          --TemplateExporter.exclude_markdown=true {} \;
      shell: sh
      working-directory: ${{ inputs.notebooks-path }}
    - name: Run bandit
      run: |
        bandit --verbose --recursive .
      shell: sh
      working-directory: ${{ inputs.notebooks-path }}
