name: Terratest Action
description: An Action to run a terratest

inputs:
  ssh_private_key_id:
    description: SSH Private key to download gruntworks repos
    required: true
  iam_creds_id:
    description: IAM Credentials Secrets Managers
    required: true
  aws_account_ids:
    description: AWS Account ID from Secrets Manager
    required: true
  aws_region:
    description: AWS Region to deploy resources
    required: true
    default: us-east-1
  terratest_args:
    description: Terratest Arguments
    required: true
    default: ""
  working_dir:
    description: Terratest Working directory
    required: true
    default: test

runs:
  using: 'docker'
  image: './Dockerfile'