name: "Global VPC Integration"
description: "Validate Plan"

inputs:
  infrastructure-path:
    description: “Path to infrastructure changes”
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run - Terraform Init"
      run: terraform init -input=false
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Validate"
      run: terraform validate
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Plan"
      id: plan
      run: terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Compliance on Action Path"
      run: |
        terraform-compliance -p plan.out.json -f ${{ github.action_path }}/features
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Compliance on Infrastructure Path"
      run: |
        terraform-compliance -p plan.out.json
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Security on Pull Request"
      if: github.event.pull_request
      uses: aquasecurity/tfsec-pr-commenter-action@main
      with:
        tfsec_args: --config-file tfsec.yml
        github_token: ${{ github.token }}
