name: "Global VPC Integration"
description: "Validate Plan"

inputs:
  infrastructure-path:
    description: “Path to infrastructure changes”
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run - Terraform Init"
      run: | 
        echo ${{ inputs.infrastructure-path }}
        echo ${{ github.action_path }}
        echo ./${{ github.action_path }}
        echo ../${{ github.action_path }}
        mkdir /usr/bin/env
        terraform init -input=false
      shell: sh
      working-directory: ./${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Validate"
      run: terraform validate
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Plan"
      id: plan
      run: terraform plan
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Comment"
      if: github.event.pull_request
      uses: actions/github-script@0.9.0
      env:
        STDOUT: "```${{ steps.plan.outputs.stdout }}```"
      with:
        github-token: ${{ github.token }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.STDOUT
          })
    - name: "Run - Terraform Security"
      if: github.event.pull_request
      uses: aquasecurity/tfsec-pr-commenter-action@main
      with:
        github_token: ${{ github.token }}
