name: "Global VPC Integration"
description: "Validate Plan"

inputs:
  infrastructure-path:
    description: “Path to infrastructure changes”
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run - Terraform Init"
      run: terraform init -input=false
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Validate"
      run: terraform validate
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Plan"
      run: terraform plan
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    - name: "Run - Terraform Apply"
      run: terraform apply -input=false -auto-approve
      shell: sh
      working-directory: ${{ inputs.infrastructure-path }}
    
