version: '3'

services:
  runner:
    image: ghcr.io/$ORGANIZATION/acuity-actions:cicd-runner
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - ORGANIZATION_ACCESS_TOKEN=$ORGANIZATION_ACCESS_TOKEN
      - ORGANIZATION=$ORGANIZATION