name: Build Image


inputs:
  repository:
    description: “Name of the repository to cache the build image”
    required: true
  deliverable:
    type: choice
    description: “Type of the image to cache”
    required: true

jobs:
  cache-cicd-image:
    runs-on: ubuntu-latest
    container: docker:20.10.9
    services:
      docker:
        image: docker:20.10.9-dind
    strategy:
        fail-fast: true
    defaults:
      run:
        working-directory: ${{ github.action_path }}/${{ github.event.inputs.deliverable }}
    steps:
      steps:
        - name: Login
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        - name: Build
          run: |
            docker build \
              --cache-from ${{ github.event.inputs.deliverable }}:cicd-${{ github.action_path }} \
              --tag ${{ github.event.inputs.deliverable }}:cicd-${{ github.action_path }} \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              "."
        - name: Push
          run: docker push ${{ github.event.inputs.deliverable }}:cicd-${{ github.action_path }}