name: Build Image


inputs:
  repository:
    description: “Name of the repository to cache the build image”
    required: true
  deliverable:
    description: “Type of the image to cache”
    required: true

env:
  CACHE_IMAGE: ghcr.io/${{ github.event.inputs.repository }}
  DOCKER_BUILDKIT: 1

runs:
  using: "composite"
  defaults:
    run:
      working-directory: ${{ github.action_path }}/${{ github.event.inputs.deliverable }}
  steps:
    - name: Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build
      run: |
        docker build \
          --cache-from ${{ github.event.inputs.repository }}:cicd-${{ github.event.inputs.deliverable }} \
          --tag ${{ github.event.inputs.repository }}:cicd-${{ github.event.inputs.deliverable }} \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          "."
    - name: Push
      run: docker push ${{ github.event.inputs.repository }}:cicd-${{ github.event.inputs.deliverable }}