name: Build Python Integration Image

on:
  push:
    paths:
      - 'build-image/python/**'
      - '.github/workflows/build-python-image.yml'

jobs:
  build-python-image:
    runs-on: ubuntu-latest
    container: docker:20.10.9
    services:
      docker:
        image: docker:20.10.9-dind
    strategy:
        fail-fast: true
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Build Python"
        uses: ./build-image/python
        with:
          repository: ${{ github.repository }}
          deliverable: python
